---
title: "Sample Code to Analyze CHIS Data"
format: 
  html:
    code-block-border-left: true
    highlight-style: github
    toc: true
    toc-depth: 4
    toc-expand: true
  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 2
    highlight-style: github
---

# Intro

This page provides sample code for appropriately analyzing California Health Interview Survey (CHIS) data in several statistical software packages using the replicate weights method or the Taylor series linearization method. For a summary of how weighting and variance estimation work in analyzing CHIS Data, refer to the page on Weighting and Variance Estimation.

CHIS employs a complex sample design and requires proper weighting and variance (or its square root – standard error) calculation of the estimates. With default settings, most statistical software packages calculate variance assuming that the data are from a simple random sample; this underestimates the variance of estimates produced from CHIS data.  

In order to accurately estimate variance in analyses of CHIS data, a complex sample, either replicate weights or the Taylor series linearization method may be used.

The final weight (rakedw0) accounts for the sample selection probabilities and statistical adjustments for potential undercoverage and nonresponse biases. In addition, when this weight is applied, it ensures that estimates from the CHIS sample are an unbiased representation of the California population. Using only rakedw0 without replicate weights rakedw1-rakedw80 or the sample design information will produce unbiased point estimates, but would underestimate the variability due to the incorrect assumption that the sample was drawn with simple random sampling.

In comparison with replicate weights, the Taylor series linearization method requires much less computing time, but requires more attention on specifying the sampling design and on appropriate handling of subpopulation analyses. The variable that accounts for sample stratification is tsvarstr. When any of the adult, adolescent, or child data files are concatenated, each household becomes like a cluster; therefore, the clustering unit variable tsvrunit should be included, but should not be included if the data files are analyzed independently of each other. If the data needs to be subset, it should be done prior to the analysis in a separate step, with the remainder of the population set to missing. 

Confidential CHIS data may utilize either replicate weights or the Taylor series linearization method. PUF data may only utilize replicate weights. The required variables for the Taylor series linearization method (tsvarstr and tsvrunit) have not been included in the CHIS Public Use Files. 



Below are sample codes.

* Replicate Weighting examples are available for:  
  - Stata, R, SAS, SUDAAN. 

* Taylor Series examples are available for:  
  - Stata, R, SAS, SUDAAN, SPSS.

* Pooling examples are available for:  
  - Stata, SAS, (R package in progress).


# Replicate Weights

This document contains information on using replicate weights to accurately calculate variance with the California Health Interview Survey (CHIS) data and also contains sample codes for generating means, frequencies, and for performing linear regressions and logistic regressions. 

In order to accurately estimate variance without jeopardizing data confidentiality and respondent privacy, CHIS Public Use Files (PUFs) provide 80 replicate weights (rakedw1-rakedw80) in addition to the final weight (rakedw0). In this document, the term “replicate weights” refers to the delete‐1 jackknife method The final weight (rakedw0) accounts for the sample selection probabilities and statistical adjustments for potential undercoverage and nonresponse biases. In addition, when this weight is applied, it ensures that estimates from the CHIS sample are an unbiased representation of the California population. The replicate weights (rakedw1-rakedw80) are specially designed for valid variance estimation in the absence of the sample design information, which have been excluded from the CHIS PUFs. These 80 different weights provide variance estimates computed with 80 replications.  
     
Confidential CHIS data may utilize either replicate weights or the Taylor series linearization method. PUF data may only utilize replicate weights.

In comparison with the Taylor series linearization method, replicate weights require no specification of the sampling design and are accurate with subset analyses (in SAS, where and by statements are safe to use with replicate weights), but replicate weights may require much more computing time compared to using the Taylor series linearization method.

When analyzing data from the CHIS PUFs, using replicate weights in conjunction with the final weight will produce unbiased estimates and variance estimations. If the final weight is applied without the replicate weights, unbiased estimates will be produced, but their variability will be underestimated due to the incorrect assumption that the sample is a simple random sample. 

Examples in this document illustrate how CHIS PUFs can be analyzed with replicate weights to produce valid variance estimates using statistical software packages.

For continuous variables, sample calculations of means and linear regression analysis are presented; for categorical variables, sample calculations of frequencies and logistic regression analysis are presented. Estimates and standard errors are identical across the software packages examined, but confidence intervals may differ because of different default methods of computation (for SAS, the default is Wald confidence intervals; for SUDAAN and Stata, it is logit confidence intervals).



## Stata

### Mean Calculation 
In the following sample code, the distribution of BMI (bmi_p) is examined by race (racehpr2) and by race and sex (racehpr2*srsex).    

```default
*Sample design specification step* 
use "DATASET LOCATION” 
svyset [pw=rakedw0], jkrw(rakedw1-rakedw80, multiplier(1)) vce(jack) mse 
  
*Analysis* 
svy: mean bmi_p, over(racehpr2) 
svy: mean bmi_p, over(srsex racehpr2) 

```
In Stata, the sample design specification step should be included before conducting any analysis. 


### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 

```default
*Sample design specification step* 
use "DATASET LOCATION” 
svyset [pw=rakedw0], jkrw(rakedw1-rakedw80, multiplier(1)) vce(jack) mse 
 
*Analysis* 
svy: tabulate astcur racehpr2, col se ci  
svy, subpop (if srsex==1): tab astcur racehpr2, col se ci 
svy, subpop (if srsex==2): tab astcur racehpr2, col se ci 

```
In Stata, the sample design specification step should be included before conducting any analysis.

Stata V.10 and higher cannot accommodate 3 or more variables in the tab command. 

### Linear Regression 
In the following sample code, Body Mass Index (bmi_p) is examined in relation to race (racehpr2), sex (srsex), and age 
(srage_p) while controlling for each other. Note that racehpr2 and srsex are categorical variables; White (racehpr2=6) and Male (srsex=1) are used as their reference categories. 

```default
*Sample design specification step* 
use "DATASET LOCATION” 
svyset [pw=rakedw0], jkrw(rakedw1-rakedw80, multiplier(1)) vce(jack) mse 
 
*Analysis*  
recode racehpr2 (6=1) (1=2) (2=3) (3=4) (4=5) (5=6) (7=7), gen(race) 
  
xi: svy: regress bmi_p i.srsex i.race srage_p 

```

In Stata, the sample design specification step should be included before conducting any analysis.

Recoding is done in order to choose “White” (racehpr2=6) as the reference group.


### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage_p). SUDAAN and Stata require the dependent variables to be coded as 0 and 1 for logistic regression, so a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 

```default
*Sample design specification step* 
use "DATASET LOCATION” 
svyset [pw=rakedw0], jkrw(rakedw1-rakedw80, multiplier(1)) vce(jack) mse 
 
*Analysis*  
recode astcur (2=0) (1=1) (-9=.), gen (ast) 
  
xi: svy: logit ast srage_p i.race i.srsex 

xi: svy: logistic ast srage_p i.race i.srsex 
```

In Stata, the sample design specification step should be included before conducting any analysis.

`logit` produces parameter estimates.

`logistic` produces odds ratios. Stata automatically chooses the lowest value of the categorical variable as the reference group for the independent and dependent variables.   


## R


### Mean Calculation 
In the following sample code, the distribution of BMI (bmi_p) is examined by race (racehpr2) and by race and sex (racehpr2*srsex).    

```default
# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svrepdesign(data = data , weights = ~ rakedw0 , 
                           repweights = "rakedw[1-80]" , 
                           type = "other" , scale = 1 ,
                           rscales = 1 , mse = TRUE)
# Analysis

chis_design |> 
  svyby( formula = ~ bmi_p , by = ~ racehpr2,
         FUN=svymean, vartype=c(“se”,”ci”), deff = TRUE)

chis_design |> 
  svyby( formula = ~ bmi_p , by = ~ racehpr2+srsex,
         FUN=svymean, vartype=c(“se”,”ci”), deff = TRUE)

```


### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 

```default
# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svrepdesign(data = data , weights = ~ rakedw0 , 
                           repweights = "rakedw[1-80]" , 
                           type = "other" , scale = 1 ,
                           rscales = 1 , mse = TRUE)
# Analysis

# sub pop 1
chis_design |> subset(srsex=="1") |> 
  svytable(formula=~astcur+racehpr2) |>
  prop.table()  # proportions

chis_design |> subset(srsex=="1") |> 
  svytable(formula=~astcur+ racehpr2) |>
  # prop.table() |> 
  summary()  # totals with chi-square stats

# sub pop 2
chis_design |> subset(srsex=="2") |> 
  svytotal(x=~interaction(astcur, racehpr2))  # total as interaction

chis_design |> subset(srsex=="2") |> 
  svymean(x=~interaction(astcur, racehpr2)) |>
  confint()  # confidence intervals

```

### Linear Regression 
In the following sample code, Body Mass Index (bmi_p) is examined in relation to race (racehpr2), sex (srsex), and age 
(srage_p) while controlling for each other. Note that racehpr2 and srsex are categorical variables; White (racehpr2=6) and Male (srsex=1) are used as their reference categories. 

```default
# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svrepdesign(data = data , weights = ~ rakedw0 , 
                           repweights = "rakedw[1-80]" , 
                           type = "other" , scale = 1 ,
                           rscales = 1 , mse = TRUE)
# Analysis

# use relevel(ref=,...) inside the formula to pick reference category
# can alternatively pre process data before the formula call

chis_design |> 
  svyglm(formula = bmi_p ~ relevel(as.factor(srsex),ref="2") + 
           relevel(as.factor(racehpr2),ref="6") + 
           srage_p,
         family=stats::gaussian(),
         rescale=TRUE) |> 
         summary()


```

### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage_p). SUDAAN and Stata require the dependent variables to be coded as 0 and 1 for logistic regression, so a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 

```default
# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svrepdesign(data = data , weights = ~ rakedw0 , 
                           repweights = "rakedw[1-80]" , 
                           type = "other" , scale = 1 ,
                           rscales = 1 , mse = TRUE)

# Analysis

# use stats::update() to transform ASTCUR after the survey design spec
# can alternatively pre process data before the survey design spec

# use relevel(ref=,...) inside the formula to pick reference category
# can alternatively pre process data before the formula call

chis_design |> 
  stats::update(ast = ifelse(astcur==2,0,1)) |>
  svyglm(formula = ast ~ srage_p + 
           relevel(as.factor(racehpr2),ref="6") + 
           relevel(as.factor(srsex),ref="2"),
         family=quasibinomial(),
         rescale=TRUE)


```

## SAS

### Mean Calculation 
In the following sample code, the distribution of BMI (bmi_p) is examined by race (racehpr2) and by race and sex (racehpr2*srsex).    

```default
SAS:   
PROC SORT DATA = data; 
BY racehpr2; 
RUN; 
 
PROC SURVEYMEANS DATA = data VARMETHOD=JACKKNIFE; 
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
VAR bmi_p; 
BY racehpr2; RUN; 
 
PROC SORT DATA = data; 
BY racehpr2 srsex; 
RUN; 
  
PROC SURVEYMEANS DATA = data VARMETHOD=JACKKNIFE; 
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
VAR bmi_p; 
BY racehpr2 srsex; 
RUN; 

```

Jackknife coefficients are necessary for accurate variance calculations, and jackknife coefficients of 1 in SAS will produce equal variance calculations as those produced in SUDAAN. However, for SAS V.9.2(TS1M0) and earlier, a value of 1 will not be accepted; as a substitute, 0.9999 can be entered. Without this specification, the default value of the jackknife coefficients will be [(# replicate weights ‐ 1)/# replicate weights]; for CHIS, this would be [(80 ‐ 1)/80] = 0.9875.

This produces racehpr2*srsex grouping.  

### Frequency Calculation 

In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 


```default
PROC SORT DATA = data; 
BY racehpr2; 
RUN; 

PROC SURVEYMEANS DATA = data VARMETHOD=JACKKNIFE; 
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
VAR astcur; 
CLASS astcur; 
BY racehpr2;  
RUN; 
 
PROC SORT DATA = data; 
BY racehpr2 srsex; 
RUN;   

PROC SURVEYMEANS DATA = data VARMETHOD=JACKKNIFE; 
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
VAR astcur; 
CLASS astcur; BY racehpr2 srsex; 
RUN;   
```

Alternatively, PROC SURVEYFREQ may be useful especially for variables with more than two categories. One caveat in creating multiple tables in one PROC SURVEYFREQ procedure is that the procedure takes the smallest applicable sample sizes among all variables. Therefore, creating one table per one PROC SURVEYFREQ procedure is recommended: 

```default
PROC SURVEYFREQ DATA = data VARMETHOD=JACKKNIFE; 
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
TABLES racehpr2*astcur/row; 
RUN; 

PROC SURVEYFREQ DATA = data VARMETHOD=JACKKNIFE; 
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
TABLES srsex*racehpr2*astcur/row; 
RUN; 

```

Jackknife coefficients are necessary for accurate variance calculations, and jackknife coefficients of 1 in SAS will produce equal variance calculations as those produced in SUDAAN. However, for SAS V.9.2(TS1M0) and earlier, a value of 1 will not be accepted; as a substitute, 0.9999 can be entered. Without this specification, the default value of the jackknife coefficients will be [(# replicate weights ‐ 1)/# replicate weights]; for CHIS, this would be [(80 ‐ 1)/80] = 0.9875. 
if data year >= 2019, then JKCOEFFS = 0.5.

This produces racehpr2*srsex grouping.  
 

### Linear Regression 

In the following sample code, Body Mass Index (bmi_p) is examined in relation to race (racehpr2), sex (srsex), and age 
(srage_p) while controlling for each other. Note that racehpr2 and srsex are categorical variables; White (racehpr2=6) and Male (srsex=1) are used as their reference categories. 

```default
PROC SURVEYREG DATA = data VARMETHOD=JACKKNIFE; 
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
FORMAT racehpr2 racehprf. srsex srsex.; 
CLASS racehpr2 srsex; 
MODEL bmi_p = srsex racehpr2 srage_p/SOLUTION;
RUN; 

```
Jackknife coefficients are necessary for accurate variance calculations, and jackknife coefficients of 1 in SAS will produce equal variance calculations as those produced in SUDAAN. However, for SAS V.9.2(TS1M0) and earlier, a value of 1 will not be accepted; as a substitute, 0.9999 can be entered. Without this specification, the default value of the jackknife coefficients will be [(# replicate weights ‐ 1)/# replicate weights]; for CHIS, this would be [(80 ‐ 1)/80] = 0.9875

When the values are formatted either in the data step or in the procedure, SAS automatically picks the category of the categorical variables whose label is alphabetically last as a reference group.

SOLUTION option provides the parameter estimates when using a CLASS statement. 

### Logistic Regression 

In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage_p). SUDAAN and Stata require the dependent variables to be coded as 0 and 1 for logistic regression, so a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 

```default
PROC SURVEYLOGISTIC DATA = data VARMETHOD=JACKKNIFE;
FORMAT astcur astcurf. racehpr2 racehprf. srsex srsex.;
WEIGHT rakedw0; 
REPWEIGHT rakedw1-rakedw80/JKCOEFS=1; 
CLASS astcur (REF=“NO CURRENT ASTHMA”) racehpr2 (REF=“WHITE”) srsex (REF=“MALE”)/PARAM=REF; 
MODEL astcur = racehpr2 srsex srage_p; 
RUN; 

```
 
When the values are formatted either in the data step or in the procedure, SAS automatically picks the category of the   	categorical variables whose label is in the last alphabetical order as a reference group.  In PROC SURVEYLOGISTIC, the   	reference category of the independent and dependent variables may be specified in a CLASS statement.

Jackknife coefficients are necessary for accurate variance calculations, and jackknife coefficients of 1 in SAS will produce equal variance calculations as those produced in SUDAAN. However, for SAS V.9.2 (TS1M0) and earlier, a value of 1 will not be accepted; as a substitute, 0.9999 can be entered. Without this specification, the default value of the jackknife coefficients will be [(# replicate weights ‐ 1)/# replicate weights]; for CHIS, this would be [(80 ‐ 1)/80] = 0.9875.

PARAM=REF is specified to ensure dummy coding of the categorical independent variables. 



## SUDAAN

### Mean Calculation 
In the following sample code, the distribution of BMI (bmi_p) is examined by race (racehpr2) and by race and sex (racehpr2*srsex).    

```default

PROC DESCRIPT DATA = data FILETYPE=SAS DESIGN=JACKKNIFE; 
WEIGHT rakedw0; 
JACKWGTS rakedw1-rakedw80/ADJJACK=1;
VAR bmi_p; 
TABLES racehpr2 racehpr2*srsex; 
SUBGROUP racehpr2 srsex; 
LEVELS 7 2; 
RUN; 

```

### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 

```default
PROC CROSSTAB DATA = data FILETYPE=SAS DESIGN=JACKKNIFE; 
WEIGHT rakedw0; 
JACKWGTS rakedw1-rakedw80/ADJJACK=1; 
TABLES racehpr2*astcur srsex*racehpr2*astcur; 
SUBGROUP astcur racehpr2 srsex; 
LEVELS 2 7 2; 
RUN; 

```

### Linear Regression 
In the following sample code, Body Mass Index (bmi_p) is examined in relation to race (racehpr2), sex (srsex), and age 
(srage_p) while controlling for each other. Note that racehpr2 and srsex are categorical variables; White (racehpr2=6) and Male (srsex=1) are used as their reference categories. 

```default
PROC REGRESS DATA = data FILETYPE=SAS DESIGN=JACKKNIFE; 
WEIGHT rakedw0; 
JACKWGTS rakedw1-rakedw80/ADJJACK=1; 
SUBGROUP racehpr2 srsex; 
LEVELS 7 2; 
REFLEVEL racehpr2=6 srsex=1; 
MODEL bmi_p = racehpr2 srsex srage_p; 
RUN; 

```


### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage_p). SUDAAN and Stata require the dependent variables to be coded as 0 and 1 for logistic regression, so a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 

```default
DATA newdata; 
SET data; 
IF astcur=1 THEN ast=1; 
ELSE IF astcur=2 THEN ast=0; 
RUN;   

PROC RLOGIST data = newdata FILETYPE=SAS DESIGN=JACKKNIFE; 
WEIGHT rakedw0; 
JACKWGTS rakedw1-rakedw80/ADJJACK=1; 
SUBGROUP racehpr2 srsex; 
LEVELS 7 2; 
REFLEVEL racehpr2 = 6 srsex = 1; 
MODEL ast = racehpr2 srsex srage_p; RUN; 

```



# Taylor Series

This document contains information on using the Taylor series linearization method to accurately calculate variance with the California Health Interview Survey (CHIS) data and also contains sample codes for generating means, frequencies, and for performing linear regressions and logistic regressions. 

The required variables for the Taylor series linearization method (tsvarstr and tsvrunit) have not been included in the CHIS Public Use Files. 
     
In comparison with replicate weights, the Taylor series linearization method requires much less computing time, but requires more attention on specifying the sampling design and on appropriate handling of subpopulation analyses. The variable that accounts for sample stratification is tsvarstr. When any of the adult, adolescent, or child data files are concatenated, each household becomes like a cluster; therefore, the clustering unit variable tsvrunit should be included, but should not be included if the data files are analyzed independently of each other. If the data needs to be subset, it should be done prior to the analysis in a separate step, with the remainder of the population set to missing. 

The final weight (rakedw0) accounts for the sample selection probabilities and statistical adjustments for potential undercoverage and nonresponse biases. In addition, when this weight is applied, it ensures that estimates from the CHIS sample are an unbiased representation of the California population. Using only rakedw0 without sample design information in analyzing CHIS data will produce unbiased estimates, but would underestimate the variability due to the incorrect assumption that the sample was drawn with simple random sampling.  

Examples in this document illustrate how CHIS data can be analyzed with Taylor series linearization to produce valid variance estimates using statistical software packages.

For continuous variables, sample calculations of means and linear regression analysis are presented; for categorical variables, sample calculations of frequencies and logistic regression analysis are presented. Estimates and standard errors are identical across the software packages examined, but confidence intervals may differ because of different default methods of computation (for SAS, the default is Wald confidence intervals; for SUDAAN and Stata, it is logit confidence intervals).




## Stata

### Mean Calculation 
In the following sample code, the distribution of BMI (bmi) is examined by race (racehpr2) and by the interaction between race and sex (racehpr2*srsex).    


```default
*Sample design specification step*
use "DATASET LOCATION” 
svyset TSVRUNIT [pw=rakedw0], strata (TSVARSTR)
  
*Analysis* 
svy: mean bmi, over(racehpr2) 
svy: mean bmi, over(srsex racehpr2) 

```

In Stata, the sample design specification step should be included before conducting any analysis.
 
When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit. 

### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 

```default
*Sample design specification step*
use "DATASET LOCATION” 
svyset TSVRUNIT [pw=rakedw0], strata (TSVARSTR)
 
*Analysis*
svy: tabulate astcur racehpr2, col se ci  
svy, subpop (if srsex==1): tab astcur racehpr2, col se ci 
svy, subpop (if srsex==2): tab astcur racehpr2, col se ci 

```

In Stata, the sample design specification step should be included before conducting any analysis.

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.

Stata V.10 and higher cannot accommodate 3 or more variables in the tab command. 

### Linear Regression 
In the following sample code, Body Mass Index (bmi) is examined in relation to race (racehpr2), sex (srsex), and age (srage) while controlling for each other. Note that racehpr2 and srsex are categorical variables, and White (racehpr2=6) and Male 
(srsex=1) are used as their reference categories. 

```default
*Sample design specification step*
use "DATASET LOCATION” 
svyset TSVRUNIT [pw=rakedw0], strata (TSVARSTR)
 
*Analysis*   
recode racehpr2 (6=1) (1=2) (2=3) (3=4) (4=5) (5=6) (7=7), gen(race)
 
xi: svy: regress bmi i.srsex i.race srage 

```

In Stata, the sample design specification step should be included before conducting any analysis.

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.

Reordering is done in order to choose “White” (racehpr2=6) as the reference group. 


### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage). As SUDAAN and Stata require the dependent variables coded as 0 and 1 for logistic regression, a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 

```default
*Sample design specification step*
use "DATASET LOCATION” 
svyset TSVRUNIT [pw=rakedw0], strata (TSVARSTR)
 
*Analysis*  
recode astcur (2=0) (1=1) (-9=.), gen (ast) 
  
xi: svy: logit ast srage i.race i.srsex 

xi: svy: logistic ast srage i.race i.srsex

```

In Stata, the sample design specification step should be included before conducting any analysis.

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.

`logit` produces parameter estimates.

`logistic`  produces odds ratios. Stata automatically chooses the lowest value of the categorical variable as the reference group for the independent and dependent variables. 


## R

The Taylor Series estimation examples in `R` using the `survey` package are exactly the same as the Replicate Weighting examples. However, the single important difference is telling `R` to change the survey design setup at the very beginning as we demonstrate below.


```default
library(survey)

# instead of ?svrepdesign() for replicate weights
# chis_design <- svrepdesign(data=your_chis_data, ... )

# use ?svydesign() for taylor series
chis_design <- svydesign(id=~tsvrunit, 
                         strata=~tsvarstr, 
                         weights=~rakedw0, 
                         data=your_chis_data,
                         nest=TRUE)

# Now, all downstream estimation functions are the same
svymean(design=chis_design, … )

```
Below are the Taylor series examples, correctly using `svydesign()` instead of `svrepdesign()`

### Mean Calculation 
In the following sample code, the distribution of BMI (bmi) is examined by race (racehpr2) and by the interaction between race and sex (racehpr2*srsex).    


```default
# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svydesign(id=~tsvrunit, 
                         strata=~tsvarstr, 
                         weights=~rakedw0, 
                         data=your_chis_data,
                         nest=TRUE)
# Analysis

chis_design |> 
  svyby( formula = ~ bmi_p , by = ~ racehpr2,
         FUN=svymean, vartype=c(“se”,”ci”), deff = TRUE)

chis_design |> 
  svyby( formula = ~ bmi_p , by = ~ racehpr2+srsex,
         FUN=svymean, vartype=c(“se”,”ci”), deff = TRUE)

```

### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 


```default
# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svydesign(id=~tsvrunit, 
                         strata=~tsvarstr, 
                         weights=~rakedw0, 
                         data=your_chis_data,
                         nest=TRUE)
# Analysis

# sub pop 1
chis_design |> subset(srsex=="1") |> 
  svytable(formula=~astcur+racehpr2) |>
  prop.table()  # proportions

chis_design |> subset(srsex=="1") |> 
  svytable(formula=~astcur+ racehpr2) |>
  # prop.table() |> 
  summary()  # totals with chi-square stats

# sub pop 2
chis_design |> subset(srsex=="2") |> 
  svytotal(x=~interaction(astcur, racehpr2))  # total as interaction

chis_design |> subset(srsex=="2") |> 
  svymean(x=~interaction(astcur, racehpr2)) |>
  confint()  # confidence intervals

```

### Linear Regression 
In the following sample code, Body Mass Index (bmi) is examined in relation to race (racehpr2), sex (srsex), and age (srage) while controlling for each other. Note that racehpr2 and srsex are categorical variables, and White (racehpr2=6) and Male 
(srsex=1) are used as their reference categories. 


```default
# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svydesign(id=~tsvrunit, 
                         strata=~tsvarstr, 
                         weights=~rakedw0, 
                         data=your_chis_data,
                         nest=TRUE)
# Analysis

# use relevel(ref=,...) inside the formula to pick reference category
# can alternatively pre process data before the formula call

chis_design |> 
  svyglm(formula = bmi_p ~ relevel(as.factor(srsex),ref="2") + 
           relevel(as.factor(racehpr2),ref="6") + 
           srage_p,
         family=stats::gaussian(),
         rescale=TRUE) |> 
         summary()


```

### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage). As SUDAAN and Stata require the dependent variables coded as 0 and 1 for logistic regression, a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 


```default

# Sample design specification step

# Developed with 'R version 4.2.3' and 'survey version 4.1-1'
library(survey)

chis_design <- svydesign(id=~tsvrunit, 
                         strata=~tsvarstr, 
                         weights=~rakedw0, 
                         data=your_chis_data,
                         nest=TRUE)

# Analysis

# use stats::update() to transform ASTCUR after the survey design spec
# can alternatively pre process data before the survey design spec

# use relevel(ref=,...) inside the formula to pick reference category
# can alternatively pre process data before the formula call

chis_design |> 
  stats::update(ast = ifelse(astcur==2,0,1)) |>
  svyglm(formula = ast ~ srage_p + 
           relevel(as.factor(racehpr2),ref="6") + 
           relevel(as.factor(srsex),ref="2"),
         family=quasibinomial(),
         rescale=TRUE)


```


## SAS

### Mean Calculation 
In the following sample code, the distribution of BMI (bmi) is examined by race (racehpr2) and by the interaction between race and sex (racehpr2*srsex).    


```default
PROC SURVEYMEANS DATA = data mean stderr NOMCAR VARMETHOD=TAYLOR;
STRATA tsvarstr; CLUSTER tsvrunit;
WEIGHT rakedw0; 
VAR bmi; 
DOMAIN racehpr2 racehpr2*srsex;
RUN; 

```


In SAS, the NOMCAR option presents the assumption that missing values are not completely at random. This, along with the DOMAIN statement, is the appropriate approach for domain analyses, which uses the entire sample for variance estimation. 

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.

If conducting a domain analysis, the DOMAIN statement is necessary for accurate variance estimation. Using BY or WHERE statements will 
not produce valid variance estimates for the subpopulation/domain. 

### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 


```default
PROC SURVEYMEANS DATA = data NOMCAR VARMETHOD=TAYLOR;
STRATA tsvarstr; CLUSTER tsvrunit; 
WEIGHT rakedw0; 
VAR astcur; 
CLASS astcur; 
DOMAIN racehpr2 racehpr2*srsex;
RUN;   

```
Alternatively, PROC SURVEYFREQ may be useful especially for the variables with more than two categories. One caveat in creating multiple tables in one PROC SURVEYFREQ procedure is that the procedure takes the smallest applicable sample sizes among all variables. Therefore, creating one table per one PROC SURVEYFREQ procedure is recommended: 

```default
PROC SURVEYFREQ DATA = data NOMCAR VARMETHOD=TAYLOR;
STRATA tsvarstr; CLUSTER tsvrunit; 
WEIGHT rakedw0; 
TABLE racehpr2*asctur/row; 
RUN;   

PROC SURVEYFREQ DATA = data NOMCAR VARMETHOD=TAYLOR;
STRATA tsvarstr; CLUSTER tsvrunit; 
WEIGHT rakedw0; 
TABLE srsex*racehpr2*astcur/row; 
RUN; 

```

In SAS, the NOMCAR option presents the assumption that missing values are not completely at random. This, along with the DOMAIN statement, is the appropriate approach for domain analyses, which uses the entire sample for variance estimation.
 
When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.
 
If conducting a domain analysis , the DOMAIN statement is necessary for accurate variance estimation. Using BY or WHERE statements will 
not produce valid variance estimates for the subpopulation/domain. 

### Linear Regression 
In the following sample code, Body Mass Index (bmi) is examined in relation to race (racehpr2), sex (srsex), and age (srage) while controlling for each other. Note that racehpr2 and srsex are categorical variables, and White (racehpr2=6) and Male 
(srsex=1) are used as their reference categories. 


```default
PROC SURVEYREG DATA = data NOMCAR VARMETHOD=TAYLOR;
STRATA tsvarstr; CLUSTER tsvrunit; 
WEIGHT rakedw0; 
FORMAT racehpr2 racehprf. srsex srsex.; 
CLASS racehpr2 srsex;
MODEL bmi = srsex racehpr2 srage/SOLUTION; 
RUN; 

```

In SAS, the NOMCAR option presents the assumption that missing values are not completely at random.  
 
When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.

When the values are formatted either in the data step or in the procedure, SAS automatically picks the category of the categorical variables whose label is alphabetically last as a reference group.

SOLUTION option provides the parameter estimates when using a CLASS statement. 

### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage). As SUDAAN and Stata require the dependent variables coded as 0 and 1 for logistic regression, a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 


```default
PROC SURVEYLOGISTIC DATA = data NOMCAR VARMETHOD=TAYLOR;
FORMAT astcur astcurf. racehpr2 racehprf. srsex srsex.;
STRATA tsvarstr; 
CLUSTER tsvrunit;
WEIGHT rakedw0; 
CLASS astcur (REF=“NO CURRENT ASTHMA”) racehpr2 (REF=“WHITE”) srsex (REF=“MALE”)/PARAM=REF;
MODEL astcur = racehpr2 srsex srage;
RUN; 

```

In SAS, the NOMCAR option presents the assumption that missing values are not completely at random. This, along with the DOMAIN statement, is the appropriate approach for domain analyses, which uses the entire sample for variance estimation.

When the values are formatted either in the data setup or in the procedure, SAS automatically picks the category of the categorical variables whose label is in the last alphabetical order as the reference group. In PROC SURVEYLOGISTIC, the reference category of the independent and dependent variables may be specified in a CLASS statement.

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.

PARAM=REF is specified to ensure dummy coding of the categorical independent variables.



## SUDAAN

### Mean Calculation 
In the following sample code, the distribution of BMI (bmi) is examined by race (racehpr2) and by the interaction between race and sex (racehpr2*srsex).    


```default
PROC SORT DATA = data; 
BY tsvarstr tsvrunit;
RUN; 
 
PROC DESCRIPTIVE DATA = data FILETYPE=SAS DESIGN=WR; 
NEST tsvarstr tsvrunit;  
WEIGHT rakedw0; 
CLASS racehpr2 racehpr2*srsex; 
VAR bmi; 
TABLES racehpr2 racehpr2*srsex; 
SUBGROUP racehpr2 srsex; 
LEVELS 7 2; 
RUN; 

```

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit. 

### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 

```default
PROC SORT DATA = data; 
BY tsvarstr tsvrunit;
RUN; 
  
PROC CROSSTAB DATA = data FILETYPE=SAS DESIGN=WR; 
NEST tsvarstr tsvrunit;  
WEIGHT rakedw0; 
TABLES racehpr2*astcur srsex*racehpr2*astcur; 
SUBGROUP astcur racehpr2 srsex; 
LEVELS 2 7 2; 
RUN; 

```

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit. 
 

### Linear Regression 
In the following sample code, Body Mass Index (bmi) is examined in relation to race (racehpr2), sex (srsex), and age (srage) while controlling for each other. Note that racehpr2 and srsex are categorical variables, and White (racehpr2=6) and Male 
(srsex=1) are used as their reference categories. 

```default
PROC SORT DATA = data; 
BY tsvarstr tsvrunit; 
RUN; 
 
PROC REGRESS DATA = data FILETYPE=SAS DESIGN=WR; 
NEST tsvarstr tsvrunit; 
WEIGHT rakedw0; 
SUBGROUP racehpr2 srsex; 
LEVELS 7 2; 
REFLEVEL racehpr2=6 srsex=1; 
MODEL bmi = racehpr2 srsex srage; 
RUN; 

```

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit. 


### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage). As SUDAAN and Stata require the dependent variables coded as 0 and 1 for logistic regression, a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 


```default
DATA newdata; 
SET data; 
IF astcur=1 THEN ast=1; 
ELSE IF astcur=2 THEN ast=0; 
RUN;   

PROC RLOGIST data = newdata FILETYPE=SAS DESIGN=WR; 
WEIGHT rakedw0; 
NEST tsvarstr tsvrunit; 
SUBGROUP racehpr2 srsex; 
LEVELS 7 2; 
REFLEVEL racehpr2 = 6 srsex = 1; 
MODEL ast = racehpr2 srsex srage; RUN; 

```


## SPSS


### Mean Calculation 
In the following sample code, the distribution of BMI (bmi) is examined by race (racehpr2) and by the interaction between race and sex (racehpr2*srsex).    


```default
*Sample design specification step*
*	Analysis Preparation Wizard. 

CSPLAN ANALYSIS 
 /PLAN FILE=‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /PLANVARS ANALYSISWEIGHT=RAKEDW0 
 /PRINT PLAN 
 /DESIGN STRATA= TSVARSTR CLUSTER=TSVRUNIT
 /ESTIMATOR TYPE=WR. 
  
*Analysis* 
*	Complex Samples Descriptives. 
CSDESCRIPTIVES 
 /PLAN FILE = ‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /SUMMARY VARIABLES = bmi 
 /SUBPOP TABLE = racehpr2 DISPLAY=LAYERED 
 /MEAN 
 /STATISTICS SE CV POPSIZE CIN (95) 
 /MISSING SCOPE = ANALYSIS CLASSMISSING = EXCLUDE. 
*	Complex Samples Descriptives. 
CSDESCRIPTIVES 
 /PLAN FILE = ‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /SUMMARY VARIABLES = bmi 
 /SUBPOP TABLE = racehpr2 BY sex DISPLAY=LAYERED 
 /MEAN 
 /STATISTICS SE CV POPSIZE CIN (95) 
 /MISSING SCOPE = ANALYSIS CLASSMISSING = EXCLUDE. 


```
In SPSS, the sample design specification step should be included before conducting any analysis.

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit. 

### Frequency Calculation 
In the following sample code, the percentage of people who currently have asthma (astcur) is examined by race (racehpr2) and by race and sex (racehpr2*srsex). 




```default
*Sample design specification step*
*	Analysis Preparation Wizard. 

CSPLAN ANALYSIS 
 /PLAN FILE=‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /PLANVARS ANALYSISWEIGHT=RAKEDW0 
 /PRINT PLAN 
 /DESIGN STRATA= TSVARSTR CLUSTER=TSVRUNIT
 /ESTIMATOR TYPE=WR. 
 
*Analysis*  
*	Complex Samples Crosstabs. 
CSTABULATE 
 /PLAN FILE = ‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /TABLES VARIABLES = astcur BY racehpr2 
 /SUBPOP TABLE = srsex DISPLAY=LAYERED 
 /CELLS POPSIZE COLPCT 
 /STATISTICS SE CV CIN (95) 
 /MISSING SCOPE = TABLE CLASSMISSING = EXCLUDE. 


```
In SPSS, the sample design specification step should be included before conducting any analysis. 

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit. 
 
 
### Linear Regression 
In the following sample code, Body Mass Index (bmi) is examined in relation to race (racehpr2), sex (srsex), and age (srage) while controlling for each other. Note that racehpr2 and srsex are categorical variables, and White (racehpr2=6) and Male 
(srsex=1) are used as their reference categories. 

```default
*Sample design specification step*
* Analysis Preparation Wizard. 

CSPLAN ANALYSIS 
 /PLAN FILE=‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /PLANVARS ANALYSISWEIGHT=RAKEDW0 
 /PRINT PLAN 
 /DESIGN STRATA= TSVARSTR CLUSTER=TSVRUNIT
 /ESTIMATOR TYPE=WR. 
 
*Analysis*   
RECODE 
srsex 
 (1=2) (2=1) INTO newsex. 
VARIABLE LABELS newsex ‘NEWSEX’. 
EXECUTE. 
 
RECODE  
racehpr2 
 (1=1) (2=2) (3=3) (4=4) (5=5) (6=7) (7=6) INTO newrace. 
 
VARIABLE LABELS newrace ‘NEWRACEHPR2’. 
EXECUTE. 

* Complex Samples General Linear Model. 
CSGLM bmi BY newsex newrace WITH srage 
 /PLAN FILE = ‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /MODEL newsex newrace srage 
 /INTERCEPT INCLUDE=YES SHOW=YES 
 /STATISTICS PARAMETER SE CINTERVAL 
 /PRINT SUMMARY VARIABLEINFO SAMPLEINFO 
 /TEST TYPE=F PADJUST=LSD 
 /MISSING CLASSMISSING=EXCLUDE 
 /CRITERIA CILEVEL=95. 

```
In SPSS, the sample design specification step should be included before conducting any analysis.

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit. 

SPSS CSGLM automatically chooses the highest value of the categorical independent variables as the reference groups. Therefore, recoding categorical variables is necessary to select the desired reference categories if they are different than the categories with the highest values. 


### Logistic Regression 
In the following sample code, current asthma status (astcur) is examined, controlling for race (racehpr2), sex (srsex), and age (srage). As SUDAAN and Stata require the dependent variables coded as 0 and 1 for logistic regression, a new dependent variable ast is created and assigned 1 where astcur=1 (“Current asthma”) and 0 where astcur=2 (“No current asthma”). The category “No current asthma” is used as the reference in the analysis. 


```default
*Sample design specification step*
* Analysis Preparation Wizard. 

CSPLAN ANALYSIS 
 /PLAN FILE=‘\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan’ 
 /PLANVARS ANALYSISWEIGHT=RAKEDW0 
 /PRINT PLAN 
 /DESIGN STRATA= TSVARSTR CLUSTER=TSVRUNIT
 /ESTIMATOR TYPE=WR. 
 
*Analysis*  

RECODE  srsex   
 (1=2) (2=1) INTO newsex.  
VARIABLE LABELS newsex 'NEWSEX'.  
EXECUTE. 
  
RECODE   racehpr2   
 (1=1) (2=2) (3=3) (4=4) (5=5) (6=7) (7=6) INTO newrace.  VARIABLE LABELS newrace 'NEWRACEHPR2'.  EXECUTE. 
  
* Complex Samples Logistic Regression.  

CSLOGISTIC astcur BY newsex newrace WITH srage  
 /PLAN FILE = '\\PATH FOR COMPLEX SURVEY PLAN FILE\FILENAME.csaplan'  
 /MODEL newsex newrace srage  
 /INTERCEPT INCLUDE=YES SHOW=YES  
 /STATISTICS PARAMETER EXP SE CINTERVAL  
 /TEST TYPE=F PADJUST=LSD  
 /ODDSRATIOS FACTOR=[newsex]  
 /ODDSRATIOS FACTOR=[newrace]  
 /ODDSRATIOS COVARIATE=[srage]  
 /MISSING CLASSMISSING=EXCLUDE  
 /CRITERIA MXITER=100 MXSTEP=5 PCONVERGE=[1e-006 RELATIVE]  
  LCONVERGE=[0] CHKSEP=20 CILEVEL=95   
/PRINT SUMMARY VARIABLEINFO SAMPLEINFO. 

```
In SPSS, the sample design specification step should be included before conducting any analysis.

When using concatenated data across adults, adolescents, and/or children, use tsvrunit; when using separate data files, delete the commands associated with tsvrunit.

SPSS CSLOGISTIC automatically chooses the highest value of the categorical variable as the reference group for the independent variables as well as the dependent variable. Therefore, recoding categorical variables is necessary to select the desired reference categories if they are different than the categories with highest values.



# Sample Code to Pool Multiple Data Cycles

For background on pooling two or more data files, see the page on Pooling.

The following Stata and SAS/SUDAAN codes show how to combine CHIS 2017 and 2018 data files and to create weights accounting for the multi-year files. In addition to the sample code, we also provide a SAS macro for the user interested in analyzing CHIS data in SAS. This SAS macro will do all the work of weight adjustments automatically, and also generate other necessary information needed in later analysis. You can download this in the section CHIS Pooling Macro.


## Stata


```default
log using "folder location\data_step.log", replace

***CHIS 2017 Adult data****
use "your folder location\CHIS 2017 data"

gen year=2017

gen fnwgt0=rakedw0/2

for new fnwgt1-fnwgt160: gen X=0

foreach i of numlist 1/80{
            local j=`i'-0
            replace fnwgt`i'=rakedw`j'/2

}

foreach i of numlist 81/160{
            replace fnwgt`i'=rakedw0/2

}

save adult17 , replace

***CHIS 2018 Adult data****
use "folder location\CHIS 2018 data"

gen year=2018

gen fnwgt0=rakedw0/2

for new fnwgt1-fnwgt160: gen X=0

foreach i of numlist 1/80{           
            replace fnwgt`i'=rakedw0/2

}

foreach i of numlist 81/160{
            local j=`i'-80
            replace fnwgt`i'=rakedw`j'/2
}

/*this step concatenates the data files*/
append using adult17 

save "folder location\combined.dta", replace

svyset [pw=fnwgt0], jkrw(fnwgt1-fnwgt160, multiplier(1)) vce(jack) mse

```

The above Stata code illustrate how to extract stored estimates from Stata commands and perform data operations based on the saved data. For Stata, returned Stata results are saved to Stata scalars and can be accessed later. For generating results from both years, users may choose to either use DISPLAY command to outputs these scalars in results window or use PUTEXCEL to save the results to an Excel file.

## SAS / SUDAAN


```default

data combined; /*this step concatenates the data files*/
	set libname.chis_2017 (in=in17) libname.chis_2018 (in=in18);
	
	if in17 then year=2017;
	else if in18 then year=2018;
	
	***Create new weight variables;
	fnwgt0 = rakedw0/2;
	array a_origwgts[80] rakedw1-rakedw80;
	array a_newwgts[160] fnwgt1-fnwgt160;
	do i = 1 to 80;
		if year=2017 then do;
			a_newwgts[i] = a_origwgts[i]/2;
			a_newwgts[i+80] = rakedw0/2;
		end;
		else if year=2018 then do;
			a_newwgts[i]    = rakedw0/2;
			a_newwgts[i+80] = a_origwgts[i]/2;
		end;

	end;
run;

proc surveyfreq data = combined varmethod=jackknife;
	weight fnwgt0;
	repweight fnwgt1-fnwgt160/jkcoefs=1;
	table ins;
run;

```

Jackknife coefficients are necessary for accurate variance calculations, and jackknife coefficients of 1 in SAS will produce equal variance calculations as those produced in SUDAAN. However, for SAS V.9.2(TS1M0) and earlier, a value of 1 will not be accepted; as a substitute, 0.9999 can be entered. Without this specification, the default value of the jackknife coefficients will be [(# replicate weights - 1)/# replicate weights]; for CHIS, this would be [(80 - 1)/80] = 0.9875.



The above SAS code illustrates how to extract stored estimates from SAS procedures and perform data operations based on the saved data.

For SAS, ODS OUTPUT statement saves the outputs from SAS procedures to a working dataset. ODS OUTPUT ONEWAY is used for one-way table, and ODS OUTPUT CROSSTABS is used for two-way crosstabs.

In this example, results are saved in the EST_COMBINED data, users may choose to use PROC PRINT to display the results in ODS window, or use PROC EXPORT to output them to an Excel file.


## CHIS Pooling Macro

In addition to the sample code above, we also provide a SAS macro for the user interested in analyzing CHIS data in SAS. This SAS macro will do all the work of weight adjustments automatically, and also generate other necessary information needed in later analysis. You can download this macro here: CHIS Pooling Macro


https://legacy.healthpolicy.ucla.edu/chis/analyze/Documents/CHIS%20POOLING%20MACRO.zip

## Video Tutorial

https://www.youtube.com/watch?v=_aQtdQWmGSc

